### ISSUE TITLE
Check the possibilities to add vscode extensions as .hsm modules

### ISSUE THREAD

**Issue by equetzal** [equetzal/huronOS-build-tools#18]

**Comment by DT3264** [comment]
Okay, so
Seems like in order for vscode / vscodium to correctly auto detect the extensions, there's should NOT be an extensions.json (the extensions already detected) nor an .obsolete file (extensions invalidated / to delete) in the extensions folder before the IDE is opened.

It might be useful in the ***.desktop*** file to use the following commands to ensure that every time, no matter if someone opened the IDE for any reason before packaging it in a module, all of the extensions existing in the extensions folder are found (PR #38 has an example and includes some documentation on how to create new extensions)

[Here's]((https://drive.google.com/file/d/1SykkXUOKM8ezwdq184werqvsJHEd-Ad1/view?usp=share_link)) an extension module example with the ***.desktop*** file updated

Regarding where to locate user-custom modules, would something like huronOS/software/extra-modules might be appropiated, or wdyt?

**Comment by DT3264** [comment]
Before that PR to exit the draft state, is required for HuronOS to be able to detect all the available modules aside from the ones in `hmm/any & hmm/all`, progress of that would be on #52
