### ISSUE TITLE
Add root password setup on intaller

### ISSUE THREAD

**Issue by equetzal** [equetzal/huronOS-build-tools#19]

**Comment by DT3264** [comment]
Added 2 alternative draft PRs regarding some ways to allow the root password to be updated on both R & R+W environments

**Comment by equetzal** [comment]
> Added 2 alternative draft PRs regarding some ways to allow the root password to be updated on both R & R+W environments

I've reviewed both of them, I like both approaches but I definitely feel that the 1st one is the stronger option, is fast and keep everything cleaner by not touching the 01-core.hsl, so I've approved that version. 

I've not tested this yet, I'll try to do it this weekend, but if you feel ready and since the script is optional to the installer, feel free to open the PR and merge it.

**Comment by DT3264** [comment]
Closing because with PR #47 the feature got integrated. the conversation prior to the merge is located in #39
