### ISSUE TITLE
Fix memory freeze with swap overload

### ISSUE THREAD

**Issue by equetzal** [equetzal/huronOS-build-tools#61]
Currently oomd executes on userspace, and kernel oomd does not act as expected because the system have present a swap of 500MiB. This swap is not useful as the system lives on the RAM, so this swap do also live in the RAM. 
The existence of this swap prevents the Kernel to act in time for the process killing, leading to at least 30 seconds of frozen screen before user-space oomd acts to recover the system.
Deactivating this swap will improve kernel-space oomd to prevent at minimum the screen freezing.

**Comment by DT3264** [comment]
Closing because #75 effectively dissabled swap and was correctly merged.
