### ISSUE TITLE
Fix dependencies on base packages

### ISSUE THREAD

**Issue by equetzal** [equetzal/huronOS-build-tools#76]
## Problem
This line:
```bash
apt install --yes --no-install-recommends "$DEPENDENCIES"
```
On the base packages, is wrong. The quotes on the package name makes apt to take that package as a single package instead of each package individually separated with spaces. 

## Solution
Rollback to:
```bash
# shellcheck disable=SC2086
apt install --yes --no-install-recommends $DEPENDENCIES
```

Or follow the [exceptions](https://www.shellcheck.net/wiki/SC2086) recommended from Shellcheck about doin this an array.

**Comment by DT3264** [comment]
Closed with merge of #78
